---
title: "Stochastic Practical"
author: "Sachin"
date: "27/01/2023"
output: html_document
---

# 1) n-step transition probability matrix
```{r}
library(expm)
a=matrix(c(0.35,0.65),ncol = 1,byrow = T)
p=matrix(c(0.7,0.3,0.4,0.6),ncol=2,byrow = T)
PT=c('P12^2','P11^4','P21^10','P(X5=1)','p(X8=2)')
Pr=c((p%^%2)[1,2],(p%^%4)[1,1],(p%^%10)[2,1],(t(a)%*%(p%^%5))[1],(t(a)%*%(p%^%8))[2])
data.frame(PT,Pr)
```
# 2) Realization of markov chain
# Q1
```{r}
s=seq(1,4,1)
a=matrix(c(0.1,0.2,0.3,0.4),ncol=1,byrow = T)
p=matrix(c(0.5,0.5,0,0,0,0.3,0.3,0.4,0.2,0.2,0.4,0.2,1,0,0,0),ncol = 4,byrow = T)
x=rep(0,5)
x[1]=sample(s,1,prob = a)
for(i in 2:5){
  x[i]=sample(s,1,prob = p[x[i-1],])
}
x
```
# Q2
```{r}
s=seq(1,3,1)
a=matrix(c(0.3,0.5,0.2),ncol = 1,byrow = T)
p=matrix(c(.3,.2,.5,.2,.5,.3,.3,.4,.3),ncol = 3,byrow =T )
x=rep(0,5)
x[1]=sample(s,1,prob=a)
for(i in 2:5){
  x[i]=sample(s,1,prob = p[x[i-1],])
}
x
```
# 3) Simulation of random walk
# Q1
```{r}
y=c(0,1,2,3,4)
s=seq(1,5,1)
n=5
a=matrix(c(.1,.2,.3,.2,.2),ncol = 1,byrow = T)
p=matrix(c(1,0,0,0,0,0.4,0,0.6,0,0,0,0.5,0,.5,0,0,0,0.2,0,0.8,0,0,0,0,1),ncol = 5,byrow = T)
x=c(0,n+1)
x[1]=sample(s,1,prob = a)
for(i in 2:n){
  x[i]=sample(s,1,prob = p[x[i-1],])
}
y[x]
```
# Q2
```{r}
y=c(0,1,2,3,4,5)
s=seq(1:5)
a=matrix(c(.1,.2,.3,.2,.2),ncol = 1,byrow = T)
p=matrix(c(1,0,0,0,0,0.4,0,0.6,0,0,0,0.5,0,.5,0,0,0,0.2,0,0.8,0,0,0,0,1),ncol = 5,byrow = T)
n=7
x=c(0,n+1)
x[1]=sample(s,1,prob=a)
for(i in 1:n){
  x[i+1]=sample(s,1,prob=p[x[i],])
}
y[x]
```
# 4) Calculation of limiting distribution of markov chain
# Q1
```{r}
library(expm)
p=matrix(c(.5,.25,.25,0,0,.25,.25,.5,.25,.5,.25,0,.25,.25,.25,.25),nrow = 4,byrow = T)
p_10=p%^%1000
zapsmall(p_10)
k=nrow(p)
A=rbind(diag(rep(1,k))-t(p),rep(1,k))
b=matrix(c(rep(0,k),1),ncol=1)
solve(t(A)%*%A,t(A)%*%b)
cat("Limitting Distribution:",(p_10[1,]),"\n")
cat("Stationary Distribution",solve(t(A)%*%A,t(A)%*%b),"\n")
```
# Q2
```{r}
p=matrix(c(0,0,0,0,1,1,0,0,0,0,.5,.5,0,0,0,1/3,1/3,1/3,0,0,1/4,1/4,1/4,1/4,0),5,5)
p_10=p%^%1000
zapsmall(p_10)
k=nrow(p)
A=rbind(diag(rep(1,k))-t(p),rep(1,k))
b=matrix(c(rep(0,k),1),ncol=1)
solve(t(A)%*%A,t(A)%*%b)
cat("Limitting Distribution:",(p_10[1,]),"\n")
cat("Stationary Distribution",solve(t(A)%*%A,t(A)%*%b),"\n")
```

# 5) Realization of Bienayme-Galton-Watson Branching Process
# Q1
```{r}
z=c(0,1,2,3)
pz=c(.2,.3,.2,.3)
x=rep(0,6)
x[1]=2
for (i in 1:5){
  x[i+1]=sum(sample(z,prob = pz,replace=T,size = x[i]))
}
x
```
# Q2)
```{r}
z=c(0,1,2,3)
pz=c(.25,.35,.3,.1)
x=rep(0,8)
x[1]=3
for(i in 1:8){
  x[i+1]=sum(sample(z,prob = pz,replace=T,size = x[i]))
}
x
```
# 6) Simulation of Poisson Process
# Q1
```{r}
lambda=2
time=5
inter=rexp(20,rate=lambda)
arr=cumsum(inter)
n=length(arr)
t1=c(0,arr)
t2=c(arr,time)
data.frame(t1,"..."=rep("<=t<",n+1),t2,Nt=seq(0,n))
```
# Q2
```{r}
lambda=1
t=c(1.5,2.2,3.8,7.5,8.8)
n=length(t)
Nt=rep(0,n)
Nt[1]=rpois(1,lambda*t[1])
for (i in 2:n){
  Nt[i]=rpois(1,lambda*t[i-1])
}
Nt=cumsum(Nt)
data.frame(t,Nt)
```
# 7) Simulation of Compound Poisson Process
# Q1
```{r}
lambda=1
time=15
inter=rexp(30,rate=lambda)
arr=cumsum(inter)
arr=arr[arr<time]
n=length(arr)
x=rnorm(n,1000,20)
zt=c(10000,10000+cumsum(x))
t1=c(0,arr)
t2=c(arr,time)
data.frame(t1,".."=rep("<=t<",n+1),t2,Nt=seq(0,n),zt)
```
# 8) M/M/1 Model
```{r}
lambda=1
mu=1.3
t=15
n=30
inter=rexp(n,lambda)
arr=cumsum(inter)
arr=arr[arr<t]
n1=length(arr)
ser=rexp(n1,mu)
dep=rep(0,n1)
dep[1]=arr[1]+ser[1]
for (i in 2:n1){
  dep[i]=max(arr[i],dep[i-1]+ser[i])
}
dep=dep[dep<t]
start=sort(c(0,arr,dep))
n=length(start)
end=sort(c(t,arr,dep))
Nt=rep(0,n)
for(i in 2:n){
  Nt[i]=sum(arr<=start[i])-sum(dep<=start[i])
}
d1=data.frame(start,to=rep(" <= t < ",n),end,Nt)
d1

```
# 9) Simulation of Renewal Process
```{r}
#lambda=2; t=5;inter=rexp(n=2*lambda*t,rate=lambda);
#mu=2;t=5;inter=rnorm(n=20,mu,sqrt(0.0625))
#alpha=2;beta=2;t=10;inter=rgamma(n=200,alpha,beta);
mu=0.5;sig2=0.0025;t=5;inter=rlnorm(n=20,mu,sqrt(sig2))
#a=0; b=5; t=15; inter=runif(n=200,a,b)
arr=cumsum(inter);
arr=arr[arr<t]
n=length(arr);
t1=c(0,arr)
ti=rep("<=t<",n+1)
t2=c(arr,t)
Nt=seq(0,n);
dat=data.frame("start"=round(t1,3),ti,"to"=round(t2,3),Nt)
dat
plot(t1,Nt,type="S")
```

